name: test-contracts

on:
  pull_request:
    branches:
      - "main"
      - "develop"
      - /^feature.*/
      - /^hotfix.*/
      - /^fix.*/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run test
        env:
          GOERLI_URL=https://eth-goerli.g.alchemy.com/v2/VGk7VsddjmGF0sFtwvf0beFxnwY5zP7s
          MUAMBAI_URL=https://polygon-mumbai.g.alchemy.com/v2/ImtiQUGhwylhGEi6M42W8-4AkyzHSONa
          PRIVATE_KEY=70160cf012d67900c6350ab95eac47ef74fdd3ef42436757413e7caa1874bacf
          PRIVATE_KEY_2=834c4795185e300c3579a390d21750a194d7efbb27b733afd22c13a7cf1c03a2
          REPORT_GAS=true
          ETHERSCAN_API_KEY=9S799ZQGQ6PG82T4APEI8J492EDX3EZI3N
          VERIFY_CONTRACT=FALSE
          COINMARKETCAP_API_KEY=89072395-d041-4ca9-bbc9-45b79d8ec517
